CREATE TABLE `family` (`id` text PRIMARY KEY NOT NULL, `name` text NOT NULL, `owner_user_id` text NOT NULL REFERENCES `user`(`id`) ON DELETE CASCADE, `created_at` integer NOT NULL);
CREATE TABLE `family_membership` (`family_id` text NOT NULL REFERENCES `family`(`id`) ON DELETE CASCADE, `user_id` text NOT NULL REFERENCES `user`(`id`) ON DELETE CASCADE, `role` text NOT NULL DEFAULT 'member', `joined_at` integer NOT NULL, PRIMARY KEY(`family_id`, `user_id`));
CREATE TABLE `family_invite` (`token` text PRIMARY KEY NOT NULL, `family_id` text NOT NULL REFERENCES `family`(`id`) ON DELETE CASCADE, `created_by` text NOT NULL REFERENCES `user`(`id`) ON DELETE CASCADE, `expires_at` integer NOT NULL);
INSERT INTO `family` (`id`, `name`, `owner_user_id`, `created_at`) SELECT 'legacy-family', 'My Family', `id`, unixepoch() * 1000 FROM `user` ORDER BY rowid LIMIT 1;
INSERT INTO `family_membership` (`family_id`, `user_id`, `role`, `joined_at`) SELECT 'legacy-family', `owner_user_id`, 'owner', unixepoch() * 1000 FROM `family` WHERE `id` = 'legacy-family';
ALTER TABLE `household_member` ADD COLUMN `family_id` text REFERENCES `family`(`id`) ON DELETE CASCADE;
ALTER TABLE `calendar` ADD COLUMN `family_id` text REFERENCES `family`(`id`) ON DELETE CASCADE;
ALTER TABLE `calendar_event` ADD COLUMN `family_id` text REFERENCES `family`(`id`) ON DELETE CASCADE;
ALTER TABLE `chore` ADD COLUMN `family_id` text REFERENCES `family`(`id`) ON DELETE CASCADE;
ALTER TABLE `allowance_ledger` ADD COLUMN `family_id` text REFERENCES `family`(`id`) ON DELETE CASCADE;
ALTER TABLE `allowance_bid` ADD COLUMN `family_id` text REFERENCES `family`(`id`) ON DELETE CASCADE;
ALTER TABLE `chore_completion` ADD COLUMN `family_id` text REFERENCES `family`(`id`) ON DELETE CASCADE;
ALTER TABLE `chore_claim` ADD COLUMN `family_id` text REFERENCES `family`(`id`) ON DELETE CASCADE;
ALTER TABLE `member_status` ADD COLUMN `family_id` text REFERENCES `family`(`id`) ON DELETE CASCADE;
ALTER TABLE `meal` ADD COLUMN `family_id` text REFERENCES `family`(`id`) ON DELETE CASCADE;
ALTER TABLE `sticky_note` ADD COLUMN `family_id` text REFERENCES `family`(`id`) ON DELETE CASCADE;
UPDATE `household_member` SET `family_id` = 'legacy-family' WHERE EXISTS (SELECT 1 FROM `family` WHERE `id` = 'legacy-family');
UPDATE `calendar` SET `family_id` = 'legacy-family' WHERE EXISTS (SELECT 1 FROM `family` WHERE `id` = 'legacy-family');
UPDATE `calendar_event` SET `family_id` = 'legacy-family' WHERE EXISTS (SELECT 1 FROM `family` WHERE `id` = 'legacy-family');
UPDATE `chore` SET `family_id` = 'legacy-family' WHERE EXISTS (SELECT 1 FROM `family` WHERE `id` = 'legacy-family');
UPDATE `allowance_ledger` SET `family_id` = 'legacy-family' WHERE EXISTS (SELECT 1 FROM `family` WHERE `id` = 'legacy-family');
UPDATE `allowance_bid` SET `family_id` = 'legacy-family' WHERE EXISTS (SELECT 1 FROM `family` WHERE `id` = 'legacy-family');
UPDATE `chore_completion` SET `family_id` = 'legacy-family' WHERE EXISTS (SELECT 1 FROM `family` WHERE `id` = 'legacy-family');
UPDATE `chore_claim` SET `family_id` = 'legacy-family' WHERE EXISTS (SELECT 1 FROM `family` WHERE `id` = 'legacy-family');
UPDATE `member_status` SET `family_id` = 'legacy-family' WHERE EXISTS (SELECT 1 FROM `family` WHERE `id` = 'legacy-family');
UPDATE `meal` SET `family_id` = 'legacy-family' WHERE EXISTS (SELECT 1 FROM `family` WHERE `id` = 'legacy-family');
UPDATE `sticky_note` SET `family_id` = 'legacy-family' WHERE EXISTS (SELECT 1 FROM `family` WHERE `id` = 'legacy-family');
UPDATE `dashboard_settings` SET `id` = 'legacy-family' WHERE `id` = 'default';
